### PR TITLE
Tweak pressure and improve 4F gestures

### LINKED ISSUE #917: drag lock when the physical button released
Hi,
when dragging with physical button pressed, the drag locks for ~2 sec after releasing the button.
There is a temporary fix [here](https://github.com/VoodooI2C/VoodooI2C/issues/290#issuecomment-629153395). But the actual fix have to be done in VoodooInput.

Thanks in advance.

### PR DESCRIPTION
**Pull request by Goshin**
This PR mainly amends the touch report definition to resolve some of the unknown bits.

- Tweak pressure to fix acidanthera/bugtracker#917.
- Amend finger touch report definition. Thanks to @stevezhengshiqi for testing and collecting data.
- Add a simple thumb detection based on the finger position, to improve some 4F gestures.

Refactor:
- Remove unused non-static function `abs()`.
- Remove wrongly named vars `x_min` and `y_min`, which are only used once.
- Rename var `finger_id` to avoid ambiguity.

### CODE REVIEW

**Comment by vit9696** [comment]
Thanks, need @usr-sse2 input.

By the way, what do we do with #14?

**Comment by Goshin** [comment]
> By the way, what do we do with #14?

@vit9696 I can rebase the pr if you want to merge #14 first, but it will be better to keep that changes in #14 minimal.

@kprinssu

**Comment by kprinssu** [comment]
I don't have much to do an in-depth review but from a quick glance it looks good. I'll leave the merge decision to @usr-sse2 and @vit9696

**Comment by vit9696** [comment]
Closing in favour of https://github.com/acidanthera/VoodooInput/pull/16.

**Comment by armenio** [comment]
Nice work. 4F gestures working fine here. (Lenovo T480)

**Pull request closed without merging**
